name: Deploy to AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: My Step
        run: echo "Hello World"
        
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          architecture: x64
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true
          job-status: success
          
      - name: Build JAR file
        run: |
          gradle build
          
      - name: Build and push Docker image to ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com
        env:
          ECR_REGISTRY: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com
          ECR_REPOSITORY: <ECR_REPOSITORY_NAME>
          IMAGE_TAG: ${{ github.sha }}
